site_bakali:
    resource: "@SiteBakaliBundle/Resources/config/routing.yml"
    prefix:   /


dash_board:
    resource: "@DashBoardBundle/Resources/config/routing.yml"
    prefix:   /


hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
facebook_login:
    pattern: /login/check-facebook
    
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login-hwi

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

