security:
  
    encoders:
        Davyb\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]    

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
            
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /dashboard/accueil
            logout:
                path:       fos_user_security_logout
                target:     /login
            remember_me:
                key:        "%secret%"
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /connect
                use_forward:       false
                failure_path:      /connect

                oauth_user_provider:
                    service: davyb.oauth.user_provider
       
        default:
            anonymous: ~

    access_control: 
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/dashboard/, role: ROLE_USER }    
        - { path: ^/, roles: ROLE_USER }   