
parameters:
    davyb.oauth.user_provider.class: Davyb\UserBundle\UserProvider

services:
    davyb.oauth.user_provider:
        class: "%davyb.oauth.user_provider.class%"
        arguments: ['@fos_user.user_manager', { facebook: facebookId }]

